#!/usr/bin/env bash
# install nginx and configures port to listen on and querying return
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/file.html
service nginx restart
