#!/usr/bin/env bash
# redirect of nginx to another page
apt-get -y update
apt-get -y install nginx
sed -i '/^\tserver_name.*/a rewrite ^/redirect_me https://www.holbertonschool.com/ permanent;' /etc/nginx/sites-available/default
service nginx restart
