#!/usr/bin/env bash
# install and configure HAproxy on server to serve as load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e '
backend web_servers
\tbalance roundrobin
\tserver 1708-web-01 35.190.151.203:80 check
\tserver 1708-web-02 54.167.86.179:80 check' >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
