#!/usr/bin/env bash
# Debugs error where sites-available/default is unlinked to site-enabled/default
service nginx stop
ln -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
