#!/usr/bin/env bash
# Uses a while loop to display Holberton School and uses
# if, elif, and else to print bad luck or good luck instead on lines 4 or 8
i="0"
while [ $i -lt 21 ]; do
    echo $i
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	esac
    i=$((i+1))
done
