#!/usr/bin/env bash
#runs nginx as nginx user
sed -i 's/80/8080/g' /etc/nginx/sites-available/default | pkill apache2
echo "user nginx;" >> /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx | sudo chmod -R u+rwx /etc/nginx
sudo -u nginx service nginx restart
